services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: tasking_module_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    networks:
      - tasking_module_network

networks:
  tasking_module_network:
    driver: bridge

